
package pl.edu.agh.soa.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentService", targetNamespace = "http://soap.soa.agh.edu.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentService {


    /**
     * 
     * @param albumNo
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentCourses", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetStudentCourses")
    @ResponseWrapper(localName = "getStudentCoursesResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetStudentCoursesResponse")
    public List<String> getStudentCourses(
        @WebParam(name = "albumNo", targetNamespace = "")
        int albumNo);

    /**
     * 
     * @param albumNo
     * @return
     *     returns pl.edu.agh.soa.soap.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentByAlbumNo", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetStudentByAlbumNo")
    @ResponseWrapper(localName = "getStudentByAlbumNoResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetStudentByAlbumNoResponse")
    public Student getStudentByAlbumNo(
        @WebParam(name = "albumNo", targetNamespace = "")
        int albumNo);

    /**
     * 
     * @param firstName
     * @param lastName
     * @param albumNo
     * @return
     *     returns pl.edu.agh.soa.soap.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addStudentWithFirstNameLastNameAlbumNo", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.AddStudentWithFirstNameLastNameAlbumNo")
    @ResponseWrapper(localName = "addStudentWithFirstNameLastNameAlbumNoResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.AddStudentWithFirstNameLastNameAlbumNoResponse")
    public Student addStudentWithFirstNameLastNameAlbumNo(
        @WebParam(name = "firstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "albumNo", targetNamespace = "")
        int albumNo);

    /**
     * 
     * @param message
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "message", targetNamespace = "")
        String message);

    /**
     * 
     * @param albumNo
     * @param course
     * @return
     *     returns pl.edu.agh.soa.soap.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCourseToStudent", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.AddCourseToStudent")
    @ResponseWrapper(localName = "addCourseToStudentResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.AddCourseToStudentResponse")
    public Student addCourseToStudent(
        @WebParam(name = "albumNo", targetNamespace = "")
        int albumNo,
        @WebParam(name = "course", targetNamespace = "")
        String course);

    /**
     * 
     * @param albumNo
     * @param course
     * @return
     *     returns pl.edu.agh.soa.soap.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteStudentCourse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.DeleteStudentCourse")
    @ResponseWrapper(localName = "deleteStudentCourseResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.DeleteStudentCourseResponse")
    public Student deleteStudentCourse(
        @WebParam(name = "albumNo", targetNamespace = "")
        int albumNo,
        @WebParam(name = "course", targetNamespace = "")
        String course);

    /**
     * 
     * @param albumNo
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvatar", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetAvatar")
    @ResponseWrapper(localName = "getAvatarResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetAvatarResponse")
    public byte[] getAvatar(
        @WebParam(name = "albumNo", targetNamespace = "")
        int albumNo);

    /**
     * 
     * @param course
     * @return
     *     returns java.util.List<pl.edu.agh.soa.soap.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentsAttendingCourse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetStudentsAttendingCourse")
    @ResponseWrapper(localName = "getStudentsAttendingCourseResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetStudentsAttendingCourseResponse")
    public List<Student> getStudentsAttendingCourse(
        @WebParam(name = "course", targetNamespace = "")
        String course);

    /**
     * 
     * @return
     *     returns java.util.List<pl.edu.agh.soa.soap.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllStudents", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetAllStudents")
    @ResponseWrapper(localName = "getAllStudentsResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetAllStudentsResponse")
    public List<Student> getAllStudents();

}
